language: php
php:
- 7.0
env:
  matrix:
  - "..."
  global:
    secure: puiHjGZIPBCivl+zh3L4X39VJMI9iK+BofZLrWV6irkXDZq+uK5IxU91CY5xrRe65BVUwqO4AkdUIexfYrVIq3IO41wsR6hQoBnFLGfccvmjfjtGmBRTu5Dy7ev0ipyWtXf7BZ27WsOkJya9TkCQn71dhihU+q1NUeajv6z2vaTX2ZT1qhConjSwzHsY1y4kps+1Ku7FlreFKBrluNg9sRhhxQy+rE74misDLv6so5+leJV7FK3aXj4Dbnj6le4ZJYffezZl90EJ1+t1eA2d0UFOhaF+9w0Z13gFYY0gJvz+oi6chhVnW0Q1BL37L+qcvF20vuoNVEyVI5/ZAhcc+TxvxfJMz6076lHEBfS7lJcPFB0QKKihvh3Sr8hEWFSUeDGa2zNdQCBeWPYqHgTXTt4HdcA+3en6I9YnAwJNCtq3100iMGeIO8QXA5fMr5dNnoEiGwl76fZN3uZ89IpJTyuP2QSa4LaDVSpSeZeOKy1whgiLS3FwYCPTIsSVHeVfy5ECAFkYd/V+fC7QE5hDCy+xfOqHnUaeliYQYLG476H+VPN9osAN58sNmfhZp5I+uA7zPFliOgsNmzWetZ6PMtiU+LbCqZVArPJQtMIRYKFlGgv5H6CV6MvBurlx3Io7IpqpFkwZ75RVuwDp/Ii09mUyyhtffKDjtF+Iug9ojlg=
before_script:
- composer install --no-progress
script:
- vendor/bin/couscous travis-auto-deploy
